/**
 * Canonical JSON schema for the HLCL build configuration.
 *
 * A single `BuildConfig` JSON document is the only data exchange between
 * the Python build pipeline and any caller (the in-browser configurator
 * and the `python hlcl/build.py --config foo.json` CLI both consume the
 * exact same shape). Defining it once with Zod gives us:
 *
 *   1. Compile-time TypeScript types (via `z.infer<…>`).
 *   2. Run-time validation with structured error messages, used when
 *      hydrating `localStorage` and when importing a user-supplied
 *      `*.json`.
 *   3. A JSON Schema sidecar (`hlcl/build-config.schema.json`, regenerated
 *      by the Vite plugin in `vite/plugins/`) that the Python
 *      `jsonschema`-style validator in `hlcl/_config.py` consumes.
 *   4. A factory-defaults sidecar (`hlcl/factory-defaults.json`,
 *      regenerated by the same Vite plugin) so `python hlcl/build.py`
 *      with no `--config` flag has a built-in fallback identical to
 *      what the configurator opens with.
 *
 * Every field name on the wire is `snake_case` so the same JSON object
 * round-trips cleanly through Python consumers.
 *
 * Schema versioning is independent for the two layers:
 *   - `BUILD_CONFIG_VERSION` is the canonical-contract version. Bump
 *     the *minor* for additive / backwards-compatible changes (a v1.0.0
 *     reader can still parse a v1.1.0 file because Zod ignores unknown
 *     fields by default and missing optional fields fall back to
 *     `.default(...)`); bump the *major* for breaking changes.
 *   - `STORAGE_VERSION` is the localStorage envelope version. It only
 *     changes when the way we persist the config (alongside UI state)
 *     changes shape, independently of the canonical config.
 */

import { z } from 'zod';

export const BUILD_CONFIG_VERSION = '1.0.0';
export const STORAGE_VERSION = '2';

// ---------------------------------------------------------------------------
// Per-family configuration
// ---------------------------------------------------------------------------

/**
 * The values a per-family option can take. Mirrors the controls
 * declared by `FamilyOption.control` in `libraries.ts`: toggle → boolean,
 * select → string, multiselect → string[], number → number, text →
 * string. We don't try to validate against the catalog at parse time
 * (the catalog evolves; old configs should still load); a downstream
 * UI step coerces unknown options back to their defaults.
 */
export const familyOptionValueSchema = z.union([
	z.boolean(),
	z.number(),
	z.string(),
	z.array(z.string())
]);
export type FamilyOptionValue = z.infer<typeof familyOptionValueSchema>;

export const familyConfigSchema = z.object({
	/** When false, this family is excluded from the build entirely. */
	enabled: z.boolean(),
	/**
	 * Per-option values keyed by `FamilyOption.id`. Unknown / removed
	 * options are tolerated (preserved in the JSON, ignored by the UI).
	 */
	options: z.record(z.string(), familyOptionValueSchema).default({}),
	/**
	 * For options with `overridesGlobal: true` in the catalog, true here
	 * means "use the per-family value", false means "inherit the
	 * corresponding `settings.hlcl.*` global". For non-overridable
	 * options the entry is absent.
	 */
	overrides: z.record(z.string(), z.boolean()).default({})
});
export type FamilyConfig = z.infer<typeof familyConfigSchema>;

// ---------------------------------------------------------------------------
// Project-wide settings (consumed by Python via `hlcl/_config.py`)
// ---------------------------------------------------------------------------

/**
 * 24-bit RGB triple in [0..255]. Both `house/altium_pcblib/footprint.py`
 * (PcbLib BodyColor3D) and `house/stepgen/colors.py` (STEP COLOUR_RGB)
 * consume these via the active `BuildConfig.settings.colors.*` block.
 */
export const rgbTupleSchema = z.tuple([
	z.number().int().min(0).max(255),
	z.number().int().min(0).max(255),
	z.number().int().min(0).max(255)
]);
export type RgbTuple = z.infer<typeof rgbTupleSchema>;

export const houseFootprintsSettingsSchema = z.object({
	priority: z.array(z.string())
});

export const ipcSettingsSchema = z.object({
	fabrication_tolerance_mm: z.number().min(0),
	placement_tolerance_mm: z.number().min(0)
});

const densityLevelSchema = z.enum(['L', 'N', 'M']);

export const hlclSettingsSchema = z.object({
	pad_corner_radius_percent: z.number().min(0).max(50),
	solder_mask_expansion_mm: z.number().min(0),
	min_solder_mask_sliver_mm: z.number().min(0),
	outline_line_width_mm: z.number().min(0),
	max_crosshair_half_arm_mm: z.number().min(0),
	component_body_standoff_mm: z.number().min(0),
	/** Global default IPC-7351B density levels to emit across all families. */
	enabled_densities: z.array(densityLevelSchema).default(['L', 'N', 'M']),
	/** Global default EIA case sizes to include across all families. */
	enabled_sizes: z
		.array(z.string())
		.default(['01005', '0201', '0402', '0603', '0805', '1206', '1210'])
});

export const stepgenSettingsSchema = z.object({
	default_fillet_radius_mm: z.number().min(0),
	resc_metal_thickness_fraction: z.number().min(0).max(1),
	resc_metal_thickness_floor_mm: z.number().min(0)
});

export const colorsSettingsSchema = z.object({
	default: z.object({ body: rgbTupleSchema }),
	capc: z.object({ body: rgbTupleSchema, terminal: rgbTupleSchema }),
	indc: z.object({ body: rgbTupleSchema, terminal: rgbTupleSchema }),
	fb: z.object({ body: rgbTupleSchema, terminal: rgbTupleSchema }),
	resc: z.object({
		substrate: rgbTupleSchema,
		passivation: rgbTupleSchema,
		terminal: rgbTupleSchema
	})
});

/**
 * Project-wide build settings. Loaded into Python by
 * `hlcl/_config.py::Settings`; legacy `from house._house_settings
 * import SETTINGS` callers reach the same object via a thin shim.
 */
export const settingsSchema = z.object({
	house_footprints: houseFootprintsSettingsSchema,
	ipc: ipcSettingsSchema,
	hlcl: hlclSettingsSchema,
	stepgen: stepgenSettingsSchema,
	colors: colorsSettingsSchema
});
export type Settings = z.infer<typeof settingsSchema>;

// ---------------------------------------------------------------------------
// Artifact emit flags
// ---------------------------------------------------------------------------

/**
 * Which artifact types the build should emit. `hlcl/build.py` consults
 * these directly via `_config.current().is_artifact_enabled(...)` to
 * decide which targets to skip when invoked under the active
 * BuildConfig — disabling `pcblib` here, for example, will skip
 * `house-pcblib` even when the user names it explicitly on the CLI.
 */
export const artifactsSchema = z.object({
	xls: z.boolean(),
	dblib: z.boolean(),
	footprints_json: z.boolean(),
	house_footprints_merge: z.boolean(),
	step_models: z.boolean(),
	pcblib: z.boolean(),
	schlib: z.boolean(),
	/**
	 * Include the populated `standards.tex` source as a download. The
	 * Python pipeline substitutes the active settings into the
	 * `docs/standards/standards.tex` template and emits the result
	 * under `build/output/standards/standards.tex`.
	 */
	standards_tex: z.boolean(),
	/**
	 * Include the populated `standards.md` rendering as a download.
	 * Same template-fill semantics as `standards_tex` but on the
	 * Markdown sibling at `docs/standards/standards.md`.
	 */
	standards_md: z.boolean(),
	zip_output: z.boolean()
});
export type Artifacts = z.infer<typeof artifactsSchema>;

// ---------------------------------------------------------------------------
// Crosslinks
// ---------------------------------------------------------------------------

export const crosslinkSchema = z.object({
	primary_mpn: z.string(),
	primary_mfg: z.string(),
	substitute_mpn: z.string(),
	substitute_mfg: z.string(),
	notes: z.string().default('')
});
export type Crosslink = z.infer<typeof crosslinkSchema>;

// ---------------------------------------------------------------------------
// BuildConfig — the canonical Python ↔ web app contract
// ---------------------------------------------------------------------------

export const buildConfigSchema = z.object({
	/** Semver. v1.x readers tolerate v1.y files; v2.x is breaking. */
	schema_version: z.literal(BUILD_CONFIG_VERSION),
	/** Vendor families to build, keyed by stable family id. */
	families: z.record(z.string(), familyConfigSchema),
	/** Project-wide settings (IPC tolerances, HLCL drawing knobs, …). */
	settings: settingsSchema,
	/** What to emit / package. */
	artifacts: artifactsSchema,
	/** MPN crosslinks for downstream BOM tools. */
	crosslinks: z.array(crosslinkSchema).default([])
});
export type BuildConfig = z.infer<typeof buildConfigSchema>;

// ---------------------------------------------------------------------------
// PersistedState — localStorage envelope
// ---------------------------------------------------------------------------

/**
 * Build-derived stats computed by `hlcl/build_stats.py` after a
 * successful in-browser build. Surfaced at the top of the configure
 * page. See `hlcl-runner.ts::BuildStats`.
 *
 * Only the two numbers that genuinely require a build live here. The
 * "Families" banner cell is computed live from the BuildConfig (just
 * the count of enabled families) so it never goes stale and isn't
 * cached.
 */
export const buildStatsSchema = z.object({
	components: z.number().int().nonnegative(),
	unique_footprints: z.number().int().nonnegative()
});
export type BuildStats = z.infer<typeof buildStatsSchema>;

/**
 * Cached build stats + a hash of the `BuildConfig` that produced them.
 * The configurator compares the hash against the live config on every
 * render: equal → numbers shown, mismatched → "???" + a "rebuild to
 * calculate" link is shown next to the banner. Persisted alongside
 * the rest of the UI session so the numbers survive a browser refresh
 * for as long as the user hasn't edited anything since the build.
 */
export const cachedBuildStatsSchema = z.object({
	stats: buildStatsSchema,
	/**
	 * Stable string fingerprint of the `BuildConfig` snapshot at the
	 * moment the build completed. Format is opaque to consumers — they
	 * only ever compare two strings for equality. Today it's a
	 * hex-encoded 32-bit FNV-1a of the JSON-stringified config (sans
	 * `crosslinks`, which don't affect what gets built).
	 */
	config_hash: z.string()
});
export type CachedBuildStats = z.infer<typeof cachedBuildStatsSchema>;

export const uiSessionSchema = z.object({
	/** Id of the last preset applied; null while user is in custom-edit mode. */
	active_preset_id: z.string().nullable().default(null),
	/** Sanitised configuration file stem (no `.json` suffix; used for downloads). */
	config_name: z.string().default('hlcl-build'),
	/**
	 * Cached library-stats from the most recent successful build, or
	 * `null` if no build has run in this browser. Defaults to `null`
	 * so existing localStorage envelopes from before this field
	 * existed continue to parse.
	 */
	build_stats: cachedBuildStatsSchema.nullable().default(null)
});
export type UiSession = z.infer<typeof uiSessionSchema>;

export const persistedStateSchema = z.object({
	/** Bumps when the localStorage shape (NOT the config schema) changes. */
	storage_version: z.literal(STORAGE_VERSION),
	config: buildConfigSchema,
	ui: uiSessionSchema
});
export type PersistedState = z.infer<typeof persistedStateSchema>;

// ---------------------------------------------------------------------------
// Defaults
// ---------------------------------------------------------------------------

/**
 * Canonical default configuration. Serialised to `hlcl/factory-defaults.json`
 * by the Vite plugin; `python hlcl/build.py` falls back to that file
 * when `--config` isn't passed.
 */
export function defaultBuildConfig(): BuildConfig {
	return {
		schema_version: BUILD_CONFIG_VERSION,
		families: {},
		settings: {
			house_footprints: {
				priority: [
					'panasonic-erj',
					'panasonic-era-a',
					'panasonic-era-v',
					'panasonic-era-p',
					'ohmite-kdv',
					'yageo-rc',
					'yageo-ac',
					'yageo-rt',
					'stackpole-rmcf',
					'stackpole-rncf',
					'samsung-capacitors',
					'tdk-capacitors',
					'murata-gcm',
					'murata-grm',
					'murata-ferrite',
					'murata-lqm',
					'murata-lqw'
				]
			},
			ipc: { fabrication_tolerance_mm: 0.1, placement_tolerance_mm: 0.05 },
			hlcl: {
				pad_corner_radius_percent: 25,
				solder_mask_expansion_mm: 0.05,
				min_solder_mask_sliver_mm: 0.1,
				outline_line_width_mm: 0.1,
				max_crosshair_half_arm_mm: 0.5,
				component_body_standoff_mm: 0.0,
				enabled_densities: ['L', 'N', 'M'],
				enabled_sizes: ['01005', '0201', '0402', '0603', '0805', '1206', '1210']
			},
			stepgen: {
				default_fillet_radius_mm: 0.05,
				resc_metal_thickness_fraction: 0.1,
				resc_metal_thickness_floor_mm: 0.02
			},
			colors: {
				default: { body: [160, 160, 160] },
				capc: { body: [184, 134, 11], terminal: [204, 204, 204] },
				indc: { body: [38, 77, 148], terminal: [204, 204, 204] },
				fb: { body: [38, 77, 148], terminal: [204, 204, 204] },
				resc: {
					substrate: [158, 158, 158],
					passivation: [23, 23, 23],
					terminal: [128, 128, 128]
				}
			}
		},
		artifacts: {
			xls: true,
			dblib: true,
			footprints_json: true,
			house_footprints_merge: true,
			step_models: true,
			pcblib: true,
			schlib: true,
			standards_tex: false,
			standards_md: false,
			zip_output: true
		},
		crosslinks: []
	};
}

export function defaultUiSession(): UiSession {
	return { active_preset_id: null, config_name: 'hlcl-build', build_stats: null };
}

export function defaultPersistedState(): PersistedState {
	return {
		storage_version: STORAGE_VERSION,
		config: defaultBuildConfig(),
		ui: defaultUiSession()
	};
}

// ---------------------------------------------------------------------------
// Vendor family catalog (catalog.json files under hlcl/vendors/<mfg>/<family>/)
// ---------------------------------------------------------------------------

/**
 * The component-kind taxonomy is closed: every vendor family is one of these.
 * Adding a new kind requires a coordinated change in `src/lib/libraries.ts`
 * (which owns the kind labels and ordering shown in the Libraries tab nav).
 */
export const componentKindSchema = z.enum(['resistor', 'capacitor', 'ferrite', 'inductor']);
export type ComponentKind = z.infer<typeof componentKindSchema>;

/**
 * A control declaration on a per-family option. Snake_case on the wire;
 * the runtime FamilyOption shape used in `libraries.ts` (camelCase)
 * is built from this in `libraries.ts::optionFromCatalog`.
 */
export const familyOptionControlCatalogSchema = z.discriminatedUnion('kind', [
	z.object({ kind: z.literal('toggle'), default_value: z.boolean() }),
	z.object({
		kind: z.literal('select'),
		choices: z.array(z.object({ id: z.string(), label: z.string() })).min(1),
		default_value: z.string()
	}),
	z.object({
		kind: z.literal('multiselect'),
		choices: z.array(z.object({ id: z.string(), label: z.string() })).min(1),
		default_value: z.array(z.string())
	}),
	z.object({
		kind: z.literal('number'),
		default_value: z.number(),
		min: z.number().optional(),
		max: z.number().optional(),
		step: z.number().optional(),
		unit: z.string().optional()
	}),
	z.object({
		kind: z.literal('text'),
		default_value: z.string(),
		placeholder: z.string().optional()
	})
]);
export type FamilyOptionControlCatalog = z.infer<typeof familyOptionControlCatalogSchema>;

export const familyOptionCatalogSchema = z.object({
	id: z.string(),
	label: z.string(),
	help: z.string().optional(),
	/** When true, the option offers a "Use global" choice in the family card. */
	overrides_global: z.boolean().optional(),
	control: familyOptionControlCatalogSchema
});
export type FamilyOptionCatalog = z.infer<typeof familyOptionCatalogSchema>;

/**
 * One vendor family catalog entry, sourced from
 * `hlcl/vendors/<manufacturer>/<family>/catalog.json`. The Vite plugin in
 * `vite/plugins/hlcl-build-assets.ts` discovers every such file at
 * dev/build time, validates it against `familyCatalogSchema` below, and
 * emits a merged `src/lib/_generated/catalog.ts` that the UI imports.
 *
 * Adding a new vendor family is therefore a pure data drop: create
 * `hlcl/vendors/<mfg>/<family>/` with a `catalog.json` and the family
 * shows up in the Libraries tab on the next dev save / CI build, with
 * zero TypeScript code changes required.
 */
export const familyCatalogEntrySchema = z.object({
	/** Stable id matching the eventual build target name, e.g. `panasonic-erj`. */
	id: z.string().min(1),
	/** Display name shown in the family card header. */
	name: z.string().min(1),
	/** Manufacturer (Panasonic, Murata, …). */
	manufacturer: z.string().min(1),
	/** Short blurb shown in the family card. */
	summary: z.string().min(1),
	/** Top-level component kind. Drives the "Resistors / Capacitors / …" tabs. */
	kind: componentKindSchema,
	/**
	 * Subtype id within the kind (e.g. `thick-film` under `resistor`). Two
	 * entries that share a `subtype_id` MUST also share a `subtype_label`
	 * — the merger emits a warning otherwise and uses the first label seen.
	 */
	subtype_id: z.string().min(1),
	/** Human-readable subtype label (e.g. "Thick film"). */
	subtype_label: z.string().min(1),
	/**
	 * Sort key controlling the order of subtypes within a kind. Lower
	 * values render first. The merger takes the minimum value seen for
	 * a given subtype across all entries, defaulting to 100.
	 */
	subtype_order: z.number().int().default(100),
	/**
	 * Sort key controlling family order within a subtype. Lower values
	 * render first; ties break alphabetically by id. Defaults to 100 so
	 * vendors that don't care about ordering get a sensible mid-value.
	 */
	sort_order: z.number().int().default(100),
	/**
	 * EIA case sizes this family ships with. Restricts the choices
	 * available in the per-family "Case sizes" multiselect; the order in
	 * the array defines the display order in the UI.
	 */
	available_sizes: z.array(z.string()).min(1),
	/**
	 * Family-specific options BEYOND the common (densities / sizes /
	 * pad-radius) options that every family gets. Use this for things
	 * like Murata GCM's `min_voltage` filter.
	 */
	options: z.array(familyOptionCatalogSchema).default([])
});
export type FamilyCatalogEntry = z.infer<typeof familyCatalogEntrySchema>;

/**
 * The merged catalog: a flat array of validated entries. The UI groups
 * them into the kind / subtype / family tree in `libraries.ts`.
 */
export const familyCatalogSchema = z.array(familyCatalogEntrySchema);
export type FamilyCatalog = z.infer<typeof familyCatalogSchema>;

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

export interface ParseResult<T> {
	ok: boolean;
	value?: T;
	errors?: string[];
}

function flattenZodIssues(err: z.ZodError): string[] {
	return err.issues.map((iss) => {
		const path = iss.path.length > 0 ? iss.path.join('.') : '<root>';
		return `${path}: ${iss.message}`;
	});
}

/**
 * Parse + validate a candidate BuildConfig (e.g. from a file the user
 * uploaded, or the result of a `JSON.parse` of imported text). Never
 * throws; returns a discriminated result the caller can render in the UI.
 */
export function parseBuildConfig(raw: unknown): ParseResult<BuildConfig> {
	const result = buildConfigSchema.safeParse(raw);
	if (result.success) return { ok: true, value: result.data };
	return { ok: false, errors: flattenZodIssues(result.error) };
}

/** Parse + validate a localStorage envelope. */
export function parsePersistedState(raw: unknown): ParseResult<PersistedState> {
	const result = persistedStateSchema.safeParse(raw);
	if (result.success) return { ok: true, value: result.data };
	return { ok: false, errors: flattenZodIssues(result.error) };
}

/**
 * Parse + validate a single per-family catalog.json. Used by the Vite
 * plugin (`vite/plugins/hlcl-build-assets.ts`) when discovering vendor
 * folders; pretty-printed errors are surfaced to the dev terminal so a
 * malformed file fails loudly rather than silently being dropped.
 */
export function parseFamilyCatalogEntry(raw: unknown): ParseResult<FamilyCatalogEntry> {
	const result = familyCatalogEntrySchema.safeParse(raw);
	if (result.success) return { ok: true, value: result.data };
	return { ok: false, errors: flattenZodIssues(result.error) };
}

// ---------------------------------------------------------------------------
// Preset files (one preset.json per file under hlcl/presets/)
// ---------------------------------------------------------------------------
//
// The hard-coded `PRESETS` list that used to live in `src/lib/presets.ts`
// has been replaced by per-preset JSON files under `hlcl/presets/`. Each
// file is a small envelope:
//
//   { id, title, tagline, description, bullets[], sort_order, config }
//
// where `config` is a normal `BuildConfig` — the same shape the Generate
// tab emits and the Import button accepts, so a preset file is fully
// round-trippable through the existing import path.
//
// The Vite plugin in `vite/plugins/hlcl-build-assets.ts` discovers every
// such file at dev/build time, validates it against `presetFileSchema`,
// and emits a merged `src/lib/_generated/presets.ts` that the
// PresetsTab imports. Adding or editing a preset is therefore a pure
// data drop: write/edit the JSON, save, and the configurator picks it
// up on the next dev save / production build.

/**
 * One preset, sourced from `hlcl/presets/<id>.json`. Field semantics:
 *
 *   - `id`         — stable identifier used in `localStorage`
 *                    (`ui.active_preset_id`); renaming is breaking.
 *   - `title`      — formatted display name for the preset card header
 *                    (e.g. "Everything · the kitchen sink"). Also seeded
 *                    into `ui.config_name` on apply (after sanitisation).
 *   - `tagline`    — short ALL-CAPS pill shown next to the title
 *                    (e.g. "Cost-optimised").
 *   - `description`— paragraph blurb under the title.
 *   - `bullets`    — green-checkmark bullet list rendered on the card.
 *                    Hand-authored so authors can pick the most
 *                    informative summary for their preset (auto-deriving
 *                    from the BuildConfig diff would lose AEC-Q200-grade,
 *                    HV-creepage style context).
 *   - `sort_order` — integer; lower renders first. Ties break by id.
 *   - `config`     — the full `BuildConfig` to apply when this preset
 *                    is chosen (crosslinks are intentionally preserved
 *                    on apply, see `AppState.applyPreset`).
 */
export const presetFileSchema = z.object({
	id: z.string().min(1),
	title: z.string().min(1),
	tagline: z.string().min(1),
	description: z.string().min(1),
	bullets: z.array(z.string().min(1)).default([]),
	sort_order: z.number().int().default(100),
	config: buildConfigSchema
});
export type PresetFile = z.infer<typeof presetFileSchema>;

/**
 * Parse + validate a single preset.json. Used by the Vite plugin when
 * discovering `hlcl/presets/*.json`; errors surface in the dev
 * terminal so a malformed file fails loudly rather than silently
 * being dropped.
 */
export function parsePresetFile(raw: unknown): ParseResult<PresetFile> {
	const result = presetFileSchema.safeParse(raw);
	if (result.success) return { ok: true, value: result.data };
	return { ok: false, errors: flattenZodIssues(result.error) };
}
