# Build databases and the autogenerated PCB footprint library for the
# passive-component repo.
#
# All generated output lands in build/, which is .gitignore'd. Each
# vendor has its own generator script under vendors/<vendor>/ that
# emits two artifacts:
#
#   build/<vendor>.xls
#       The database workbook the matching build/<vendor>.DbLib binds
#       to inside Altium. Excel 97-2003 BIFF8 format.
#   build/footprints/<vendor>-footprints.json
#       Per-vendor specification of the unique CAPC/RESC/INDC
#       footprints (x density variants L/N/M) the database above
#       references. JSON schema is defined in vendors/_common.py.
#
# After every per-vendor script has run, `make house-footprints` (also
# wired into `make all`) merges every build/footprints/*-footprints.json
# into a single build/footprints/house-footprints.json. The merge
# uses the priority list in settings.toml to break FootprintName ties.
#
# `make house-step-models` then runs house/build_step_models.py, a
# Python driver that reads the merged JSON and emits one parametric
# STEP 3D model per footprint into build/step/<FootprintName>.step.
# The geometry engine lives in house/stepgen/ and is intentionally
# pure-stdlib Python so the whole 3D model generator can eventually
# run in a browser (Pyodide) for an open-source web UI.
#
# `make house-pcblib` finally runs the autogenerator under
# house/altium_pcblib/ -- a pure-stdlib Python package that consumes
# house-footprints.json + build/step/*.step and emits
# build/house.PcbLib directly, applying IPC-7351B pad math (Tables
# 3-5/3-6) and the DDL-001 drawing standards (rounded-rect 25%-radius
# pads, manual 0.05mm solder mask expansion, 3D body on Mech 1,
# outline + centroid on Mech 15) and embedding each STEP file inline
# (zlib-compressed) so the .pcblib has zero external file deps.
#
# Each target also copies its .DbLib from vendors/<vendor>/hardcoded/
# into build/. The hardcoded copy is the checked-in source of truth;
# edit it there, not in build/. `make` copies so the DbLib sits next
# to its .xls (the DatabasePathRelative=1 setting inside the DbLib
# requires them to be siblings).
#
# Reminder: after regenerating any database .xls, open it in Microsoft
# Excel and re-save (keeping the .xls Excel 97-2003 format) before
# Altium will read it. See the "Regenerating the Databases" section
# of README.md.
#
# Usage:
#   make                     same as `make all`
#   make all                 build every vendor database, merge the
#                            per-vendor footprints JSONs, generate
#                            STEP models, and assemble build/house.PcbLib
#   make panasonic           build build/panasonic-resistors.{xls,DbLib}
#                            + build/footprints/panasonic-resistors-footprints.json
#   make tdk-capacitors      build build/tdk-capacitors.{xls,DbLib}
#                            + build/footprints/tdk-capacitors-footprints.json
#   make samsung-capacitors  build build/samsung-capacitors.{xls,DbLib}
#                            + build/footprints/samsung-capacitors-footprints.json
#   make murata-ferrites     copy build/murata-ferrite.DbLib from hardcoded/
#                            and run the murata-ferrite generator (currently
#                            a no-op placeholder; see vendors/murata/murata-ferrite.py)
#   make murata-capacitors   build build/murata-capacitors.xls from
#                            vendors/murata/gcm_parts.csv (refresh the CSV
#                            with `python vendors/murata/fetch_gcm_pim.py`
#                            when you want to pull the latest MPN list),
#                            plus copy the matching DbLib from hardcoded/,
#                            plus build/footprints/murata-capacitors-footprints.json
#   make house-footprints    merge per-vendor footprints JSONs into
#                            build/footprints/house-footprints.json
#                            (priority resolution per settings.toml)
#   make house-step-models   generate parametric STEP 3D models for every
#                            chip footprint into build/step/*.step via
#                            the pure-Python engine in house/stepgen/
#   make house-pcblib        autogenerate build/house.PcbLib from the
#                            merged JSON + STEP models via
#                            house/altium_pcblib (pure-stdlib Python;
#                            implements MS-CFB v3 + AltiumSharp v1.0.2's
#                            record format directly). STEP models are
#                            zlib-embedded so the .pcblib stands alone.
#   make clean               remove generated files from build/
#
# Overrides:
#   make PYTHON=py            use a different Python launcher (default: python)
#   make CP=install           use a different copy command (default: cp)

PYTHON         ?= python
CP             ?= cp
BUILD_DIR      := build
FOOTPRINTS_DIR := $(BUILD_DIR)/footprints
STEP_DIR       := $(BUILD_DIR)/step
PCBLIB_DIR     := house/altium_pcblib
STEPGEN_DIR    := house/stepgen

# Per-vendor footprint JSONs that must exist before the merge step.
VENDOR_FOOTPRINT_JSON := \
	$(FOOTPRINTS_DIR)/panasonic-resistors-footprints.json \
	$(FOOTPRINTS_DIR)/tdk-capacitors-footprints.json      \
	$(FOOTPRINTS_DIR)/samsung-capacitors-footprints.json  \
	$(FOOTPRINTS_DIR)/murata-capacitors-footprints.json

# Sources that, when changed, should force a rebuild of build/house.PcbLib.
PCBLIB_SRCS := \
	house/build_pcblib.py \
	$(PCBLIB_DIR)/__init__.py \
	$(PCBLIB_DIR)/binary.py \
	$(PCBLIB_DIR)/cfb.py \
	$(PCBLIB_DIR)/ddl.py \
	$(PCBLIB_DIR)/footprint.py \
	$(PCBLIB_DIR)/ipc.py \
	$(PCBLIB_DIR)/primitives.py \
	$(PCBLIB_DIR)/records.py \
	$(PCBLIB_DIR)/writer.py \
	$(PCBLIB_DIR)/_library_params_template.txt

# Sources that, when changed, should force a rebuild of build/step/*.step.
# Listed individually (rather than $(wildcard ...)) so adding a new file
# requires an explicit Makefile change -- keeps the dependency surface
# obvious for someone reading the build.
STEPGEN_SRCS := \
	house/build_step_models.py \
	$(STEPGEN_DIR)/__init__.py \
	$(STEPGEN_DIR)/chip.py \
	$(STEPGEN_DIR)/colors.py \
	$(STEPGEN_DIR)/doc.py \
	$(STEPGEN_DIR)/filleted.py \
	$(STEPGEN_DIR)/shapes.py

.PHONY: all clean panasonic tdk-capacitors samsung-capacitors murata-ferrites murata-capacitors house-footprints house-step-models house-pcblib

all: panasonic tdk-capacitors samsung-capacitors murata-ferrites murata-capacitors house-footprints house-step-models house-pcblib

panasonic:          $(BUILD_DIR)/panasonic-resistors.xls  $(BUILD_DIR)/panasonic-resistors.DbLib
tdk-capacitors:     $(BUILD_DIR)/tdk-capacitors.xls       $(BUILD_DIR)/tdk-capacitors.DbLib
murata-ferrites:    $(BUILD_DIR)/murata-ferrite.xls       $(BUILD_DIR)/murata-ferrite.DbLib
murata-capacitors:  $(BUILD_DIR)/murata-capacitors.xls    $(BUILD_DIR)/murata-capacitors.DbLib
samsung-capacitors: $(BUILD_DIR)/samsung-capacitors.xls   $(BUILD_DIR)/samsung-capacitors.DbLib
house-footprints:   $(FOOTPRINTS_DIR)/house-footprints.json
house-step-models:  $(STEP_DIR)/.stamp
house-pcblib:       $(BUILD_DIR)/house.PcbLib

# Each per-vendor script writes BOTH its database .xls and its
# footprints .json in one invocation, so the .json is a co-output of
# the same recipe that builds the .xls. Declared as a GNU make grouped
# target (`&:`, requires make 4.3+) so make doesn't try to rebuild
# the script twice when both outputs are demanded.
$(BUILD_DIR)/panasonic-resistors.xls $(FOOTPRINTS_DIR)/panasonic-resistors-footprints.json &: \
		vendors/panasonic/panasonic-resistors.py vendors/_common.py
	$(PYTHON) vendors/panasonic/panasonic-resistors.py

$(BUILD_DIR)/tdk-capacitors.xls $(FOOTPRINTS_DIR)/tdk-capacitors-footprints.json &: \
		vendors/tdk/tdk-capacitors.py vendors/tdk/tdk_automotive_pn.csv vendors/_common.py
	$(PYTHON) vendors/tdk/tdk-capacitors.py

# NOTE: murata-ferrite.py is currently a placeholder that does not write its
# output file, so the `.xls` mtime never gets bumped and this recipe will
# re-run on every `make` invocation. That's fine while the generator is
# stubbed (the script only prints a reminder). Once the generator is filled
# in and actually writes OUTPUT_XLS, the normal make dependency tracking
# will take over. Also: build/murata-ferrite.xls is NOT in the clean target
# because today it's hand-maintained, not generated -- `make clean` must
# not delete it.
$(BUILD_DIR)/murata-ferrite.xls: vendors/murata/murata-ferrite.py
	$(PYTHON) $<

# murata-capacitors.xls depends on the Murata PIM CSV that vendors/murata/fetch_gcm_pim.py
# downloads. The CSV is checked in so the default build is offline / reproducible;
# run `python vendors/murata/fetch_gcm_pim.py` manually when you want to refresh it.
$(BUILD_DIR)/murata-capacitors.xls $(FOOTPRINTS_DIR)/murata-capacitors-footprints.json &: \
		vendors/murata/murata-capacitors.py vendors/murata/gcm_parts.csv vendors/_common.py
	$(PYTHON) vendors/murata/murata-capacitors.py

$(BUILD_DIR)/samsung-capacitors.xls $(FOOTPRINTS_DIR)/samsung-capacitors-footprints.json &: \
		vendors/samsung/samsung-capacitors.py vendors/samsung/filtered_samsung_mlcc.csv vendors/_common.py
	$(PYTHON) vendors/samsung/samsung-capacitors.py

# build/footprints/house-footprints.json is the priority-merged union
# of every per-vendor footprints JSON. settings.toml at the repo root
# defines the conflict-resolution priority list. Schema is defined in
# vendors/_common.py and validated on read by the merge script.
$(FOOTPRINTS_DIR)/house-footprints.json: \
		house/build_house_footprints.py settings.toml $(VENDOR_FOOTPRINT_JSON)
	$(PYTHON) house/build_house_footprints.py

# build/step/*.step are the parametric 3D models for each unique chip
# body, generated by the pure-Python engine in house/stepgen/. The
# IPC-7351B density variants (L / N / M) only differ in pad geometry,
# not in component body, so there is one STEP per *footprint root*
# (FootprintName minus its trailing density letter), e.g.
#
#   build/step/CAPC0402X20.step  -- shared by CAPC0402X20{L,N,M}
#
# These files are consumed by:
#
#   - the .pcblib autogenerator below, which embeds them into the
#     library so the .pcblib is standalone (no external file refs);
#     all three density variants of a root reference the same STEP
#     body and AltiumSharp embeds it once per variant;
#   - humans, who can open them in any STEP viewer to inspect the 3D
#     geometry of a specific chip body.
#
# All STEP files come out of one Python invocation, so we track build
# state with a stamp file.
$(STEP_DIR)/.stamp: $(STEPGEN_SRCS) $(FOOTPRINTS_DIR)/house-footprints.json
	@mkdir -p $(STEP_DIR)
	$(PYTHON) house/build_step_models.py
	@touch $@

# build/house.PcbLib is the autogenerated Altium PCB footprint library:
# every CAPC/RESC chip footprint listed in house-footprints.json, drawn
# per docs/standards/DDL-001.tex (rounded-rect pads with 25% radius,
# manual 0.05mm solder mask expansion, 3D body on Mech 1, outline +
# centroid on Mech 15, no silkscreen, no courtyard) and sized per IPC-
# 7351B Tables 3-5/3-6. Each component body has its parametric 3D
# model embedded in-place from build/step/<FootprintRoot>.step.
#
# The writer is pure-stdlib Python under house/altium_pcblib/. It
# implements MS-CFB v3 + AltiumSharp v1.0.2's record format directly,
# so there are no external dependencies (no .NET SDK, no AltiumSharp,
# no OpenMcdf). Output is byte-stable across builds (deterministic
# DATE/TIME placeholders + content-derived 3D model GUIDs).
$(BUILD_DIR)/house.PcbLib: $(FOOTPRINTS_DIR)/house-footprints.json $(STEP_DIR)/.stamp $(PCBLIB_SRCS)
	@mkdir -p $(BUILD_DIR)
	$(PYTHON) house/build_pcblib.py \
	    --input    $(FOOTPRINTS_DIR)/house-footprints.json \
	    --output   $@ \
	    --step-dir $(STEP_DIR)

# DbLib files live in vendors/<name>/hardcoded/ (checked into git) and are
# copied verbatim into build/ so each .DbLib sits next to its .xls. Never
# hand-edit the build/ copies; the next `make` will blow them away.
$(BUILD_DIR)/panasonic-resistors.DbLib: vendors/panasonic/hardcoded/panasonic-resistors.DbLib
	@mkdir -p $(BUILD_DIR)
	$(CP) $< $@
$(BUILD_DIR)/tdk-capacitors.DbLib: vendors/tdk/hardcoded/tdk-capacitors.DbLib
	@mkdir -p $(BUILD_DIR)
	$(CP) $< $@
$(BUILD_DIR)/samsung-capacitors.DbLib: vendors/samsung/hardcoded/samsung-capacitors.DbLib
	@mkdir -p $(BUILD_DIR)
	$(CP) $< $@
$(BUILD_DIR)/murata-capacitors.DbLib: vendors/murata/hardcoded/murata-capacitors.DbLib
	@mkdir -p $(BUILD_DIR)
	$(CP) $< $@
$(BUILD_DIR)/murata-ferrite.DbLib: vendors/murata/hardcoded/murata-ferrite.DbLib
	@mkdir -p $(BUILD_DIR)
	$(CP) $< $@

clean:
	$(RM) $(BUILD_DIR)/panasonic-resistors.xls
	$(RM) $(BUILD_DIR)/tdk-capacitors.xls
	$(RM) $(BUILD_DIR)/murata-capacitors.xls
	$(RM) $(BUILD_DIR)/samsung-capacitors.xls
	$(RM) $(FOOTPRINTS_DIR)/panasonic-resistors-footprints.json
	$(RM) $(FOOTPRINTS_DIR)/tdk-capacitors-footprints.json
	$(RM) $(FOOTPRINTS_DIR)/murata-capacitors-footprints.json
	$(RM) $(FOOTPRINTS_DIR)/samsung-capacitors-footprints.json
	$(RM) $(FOOTPRINTS_DIR)/house-footprints.json
	$(RM) $(BUILD_DIR)/house.PcbLib
	$(RM) -r $(STEP_DIR)
	$(RM) $(BUILD_DIR)/panasonic-resistors.DbLib
	$(RM) $(BUILD_DIR)/tdk-capacitors.DbLib
	$(RM) $(BUILD_DIR)/murata-capacitors.DbLib
	$(RM) $(BUILD_DIR)/murata-ferrite.DbLib
	$(RM) $(BUILD_DIR)/samsung-capacitors.DbLib
	$(RM) -r $(STEPGEN_DIR)/__pycache__
	$(RM) -r $(PCBLIB_DIR)/__pycache__
	$(RM) -r vendors/__pycache__
	$(RM) -r house/__pycache__
