#!/usr/bin/env python
"""
Top-level build orchestrator for Humanity's Last Component Library.

Replaces the (deleted) recursive Makefile system. Runs every per-vendor
family generator, merges per-vendor footprints JSONs into the canonical
``build/intermediate/footprints/house-footprints.json``, generates
parametric STEP 3D models, copies in the hand-maintained
``house.SchLib``, and emits ``build/output/house.PcbLib`` -- all
in-process, never via ``subprocess``.

The "in-process" property is load-bearing: the same module drives the
build from a host CLI today and from Pyodide in the browser tomorrow.
Pyodide can't fork shells, so every step had to be callable as a
Python function. Vendor scripts already had argv-driven ``main()``
entrypoints, so the orchestrator just imports each one (via
``importlib.util.spec_from_file_location``, since the scripts have
dashes in their basenames and so can't be imported by name) and calls
``main()``.

Discovery
---------
Each vendor family folder under ``vendors/<mfg>/<family>/`` and each
house component folder under ``house/<component>/`` ships a tiny
``_build.py`` that calls :func:`register` at import time. ``build.py``
globs those files and imports them; **no top-level edit is required to
add a new family** -- mirroring the old Makefile chain's
``+= VENDOR_TARGETS`` ergonomic.

Configuration
-------------
Every invocation runs against a :class:`hlcl._config.BuildConfig`
loaded from JSON. The default path is ``hlcl/factory-defaults.json``
(auto-generated by the Vite plugin from the canonical Zod schema in
``src/lib/schema.ts``); override with ``--config <path>``. The JSON
contract is the only data exchange between Python and the in-browser
configurator -- there is no separate ``settings.toml`` any more.

The active config gates which targets run:

* ``vendor`` targets execute iff ``families.<id>.enabled`` is true AND
  any of the ``artifacts.{xls, dblib, footprints_json}`` flags is set.
* ``house`` targets execute iff their corresponding artifact flag is
  set (``house-pcblib`` ↔ ``artifacts.pcblib`` etc.).
* ``aggregate`` targets always run (they're no-op phonies whose only
  job is to pull deps in; the deps themselves get filtered).

CLI
---
::

    python build.py [--config <path>]
                                       same as ``all`` against the
                                       active config (or
                                       ``hlcl/factory-defaults.json``
                                       if no ``--config``)
    python build.py [--config <path>] all
                                       build every config-enabled target
    python build.py [--config <path>] <target>
                                       build one target plus its deps,
                                       respecting config gates on the
                                       transitive deps
    python build.py clean              rm -rf build/ + __pycache__
                                       (no config required)
    python build.py --list             print every registered target
                                       and its config-derived gate
                                       state

Library API
-----------
::

    import build
    build.discover(root='/hlcl', config_path='/hlcl/build-config.json')
    build.build_all()
    build.build_target("murata-gcm")
    build.clean()

When called from Pyodide, pass ``root='/hlcl'`` and
``config_path='/hlcl/build-config.json'`` so the in-MEMFS layout
matches the orchestrator's expectations.
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import sys
from dataclasses import dataclass
from glob import glob
from typing import Callable, Iterable

import _config

# The directory that contains this build.py. Every other path in the
# orchestrator is resolved relative to ROOT_DIR; nothing reads
# os.getcwd(). This is what lets Pyodide drive the build after
# mounting the source tree at an arbitrary path in its in-memory FS.
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

# Special pseudo-dep: house targets use this to mean "every registered
# vendor target". The expansion happens lazily at build_target() time,
# so dropping in a new vendors/<mfg>/<family>/_build.py automatically
# becomes a prerequisite of house-footprints (and transitively of
# house-step-models / house-pcblib).
ALL_VENDORS = "@vendors"

VENDOR = "vendor"
HOUSE = "house"
AGGREGATE = "aggregate"
VALID_KINDS = frozenset({VENDOR, HOUSE, AGGREGATE})


@dataclass
class Target:
    name: str
    kind: str
    runner: Callable[[], None]
    deps: tuple[str, ...] = ()
    cli_only: bool = False


_REGISTRY: dict[str, Target] = {}
_DISCOVERED = False


# ---------------------------------------------------------------------------
# Registration (called by every _build.py stub)
# ---------------------------------------------------------------------------

def register(
    name: str,
    *,
    kind: str,
    runner: Callable[[], None],
    deps: Iterable[str] = (),
    cli_only: bool = False,
) -> None:
    """Declare a build target. Called from each ``_build.py`` stub at
    import time.

    ``kind`` is one of ``vendor`` / ``house`` / ``aggregate``. ``runner``
    is a zero-arg callable that performs the build. ``deps`` is a tuple
    of target names; the special string ``@vendors`` expands at
    execution time to every currently-registered vendor target (this
    is what house-footprints uses so adding a new family is automatic).
    Targets flagged ``cli_only=True`` are skipped by :func:`build_all`
    and so don't run inside Pyodide. No registered target sets this
    flag today (the previous pdflatex-driven ``standards`` target was
    retired in favour of the in-process template renderer), but the
    flag is retained for any future host-only target that might shell
    out to a native tool.
    """
    if kind not in VALID_KINDS:
        raise ValueError(
            f"target {name!r}: kind must be one of {sorted(VALID_KINDS)} (got {kind!r})"
        )
    if name in _REGISTRY:
        raise ValueError(f"target {name!r} already registered")
    _REGISTRY[name] = Target(
        name=name, kind=kind, runner=runner, deps=tuple(deps), cli_only=cli_only,
    )


def call_main(mod, argv: Iterable[str] = ()) -> int:
    """Invoke ``mod.main`` after temporarily patching ``sys.argv`` so
    argparse-driven entrypoints see the desired flags. Restores
    ``sys.argv`` on exit so subsequent targets see clean argv.

    Works uniformly for every flavour of generator script in this
    repo: vendor scripts whose ``main()`` takes no arguments (they
    read ``sys.argv`` via ``argparse``), house scripts that don't use
    argparse at all (``build_house_footprints.py``,
    ``build_step_models.py``), and ``build_pcblib.py`` whose
    ``main(argv)`` defaults ``argv=None`` and so falls through to
    ``sys.argv``.

    A handful of legacy vendor scripts (e.g. ``tdk-capacitors.py``)
    put their whole body at module scope rather than under a
    ``def main():``. For those the import done by :func:`load_module`
    already performed the build, and we just return 0 -- the runner
    re-executes the file from scratch on every invocation because
    :func:`load_module` always allocates a fresh module object.
    """
    saved_argv = sys.argv
    try:
        sys.argv = [getattr(mod, "__file__", "<build>")] + list(argv)
        main_fn = getattr(mod, "main", None)
        if main_fn is None:
            return 0
        rc = main_fn()
        return rc if isinstance(rc, int) else 0
    finally:
        sys.argv = saved_argv


def load_module(path: str, module_name: str | None = None):
    """Import a single Python file at ``path`` as a module and return
    it. Used by vendor ``_build.py`` stubs to pull in their
    ``<vendor>-<family>.py`` sibling, whose dashed basename can't be
    ``import``ed normally. Also used internally by :func:`discover`
    to load ``_build.py`` stubs themselves.

    Each module gets a unique synthetic ``module_name`` so multiple
    files with the same basename (e.g. several ``_build.py``) coexist
    in ``sys.modules`` without clobbering one another.
    """
    if module_name is None:
        rel = os.path.relpath(path, ROOT_DIR)
        module_name = "_hlcl_loaded__" + (
            rel.replace(os.sep, "_").replace("/", "_").replace("-", "_").replace(".py", "")
        )
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"could not load module at {path!r}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = mod
    spec.loader.exec_module(mod)
    return mod


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def discover(
    root: str | None = None,
    config_path: str | None = None,
    config: _config.BuildConfig | None = None,
) -> _config.BuildConfig:
    """Find every ``_build.py`` under ``vendors/`` and ``house/``, then
    import each so that the ``register(...)`` calls inside land in
    ``_REGISTRY``. Idempotent on target registration.

    The active :class:`_config.BuildConfig` is installed (via
    :func:`_config.set_current`) BEFORE any ``_build.py`` is loaded, so
    that vendor / house modules importing ``_house_settings.SETTINGS``
    (or calling ``_config.current()``) at module scope see a populated
    config. Resolution order, highest precedence first:

      1. The ``config`` kwarg, if provided.
      2. The JSON file at ``config_path``, if provided.
      3. ``hlcl/factory-defaults.json`` next to this build.py
         (the Vite plugin emits this).
      4. ``--config <path>`` peeled off ``sys.argv`` by
         :func:`_config.bootstrap`.

    Returns the installed config so callers can read it back without
    re-import.
    """
    global _DISCOVERED

    # Install the active config first; ``_build.py`` stubs and house
    # modules read from ``_config.current()`` at import time.
    if config is not None:
        cfg = _config.set_current(config)
    elif config_path is not None:
        cfg = _config.set_current(_config.load(config_path))
    else:
        # Falls back to factory-defaults.json or `--config` in argv.
        cfg = _config.bootstrap()

    if _DISCOVERED:
        return cfg
    base = os.path.abspath(root) if root else ROOT_DIR
    patterns = [
        os.path.join(base, "vendors", "*", "*", "_build.py"),
        os.path.join(base, "house", "_build.py"),
        os.path.join(base, "house", "*", "_build.py"),
    ]
    for pattern in patterns:
        for path in sorted(glob(pattern)):
            load_module(path)
    _register_manufacturer_aggregates()
    _DISCOVERED = True
    return cfg


def _register_manufacturer_aggregates() -> None:
    """Auto-create per-manufacturer aggregate phonies from the prefix
    each vendor target shares before its first dash. The convention
    the old top-level Makefile documented -- ``make panasonic`` builds
    every ``panasonic-*`` family in one shot -- generalised to every
    manufacturer with 2+ family targets registered."""
    by_prefix: dict[str, list[str]] = {}
    for t in _REGISTRY.values():
        if t.kind != VENDOR:
            continue
        prefix, sep, _ = t.name.partition("-")
        if not sep:
            continue
        by_prefix.setdefault(prefix, []).append(t.name)
    for prefix, members in by_prefix.items():
        if prefix in _REGISTRY:
            continue  # don't shadow an existing target
        if len(members) < 2:
            continue  # single-family manufacturer doesn't need an aggregate
        register(
            prefix,
            kind=AGGREGATE,
            runner=_noop,
            deps=tuple(sorted(members)),
        )


def _noop() -> None:
    """Aggregate targets are pure dep nodes -- their runner is a no-op."""


# ---------------------------------------------------------------------------
# Target resolution / execution
# ---------------------------------------------------------------------------

def list_targets() -> list[Target]:
    """Return every registered target, sorted (kind, name)."""
    discover()
    return sorted(_REGISTRY.values(), key=lambda t: (t.kind, t.name))


def _resolve_deps(name: str) -> list[str]:
    """Return ``name``'s deps in topological order (deps first),
    expanding the ``@vendors`` pseudo-dep to every currently-registered
    vendor target. Raises on cycles."""
    if name not in _REGISTRY:
        raise KeyError(
            f"unknown target {name!r}; available: {sorted(_REGISTRY)}"
        )
    order: list[str] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(n: str) -> None:
        if n in visited:
            return
        if n in visiting:
            raise RuntimeError(f"dependency cycle detected at {n!r}")
        visiting.add(n)
        for d in _REGISTRY[n].deps:
            if d == ALL_VENDORS:
                for t in _REGISTRY.values():
                    if t.kind == VENDOR:
                        visit(t.name)
            else:
                visit(d)
        visiting.discard(n)
        visited.add(n)
        order.append(n)

    visit(name)
    return order


def build_target(
    name: str,
    root: str | None = None,
    config_path: str | None = None,
    config: _config.BuildConfig | None = None,
) -> None:
    """Run ``name`` plus its (transitive) deps in topological order.

    Config-disabled deps along the chain are still SKIPPED at execution
    time (a disabled vendor doesn't get re-enabled just because the
    user explicitly asked for the downstream merge). The explicitly
    requested ``name`` itself, however, runs unconditionally -- if the
    user typed ``python build.py murata-gcm`` they want it built even
    if their saved config has it disabled.
    """
    cfg = discover(root, config_path=config_path, config=config)
    requested = name
    for n in _resolve_deps(name):
        t = _REGISTRY[n]
        if t.cli_only:
            continue
        if n != requested and not cfg.is_target_enabled(n, t.kind):
            print(f"--> skipping {t.name} (disabled by config)", file=sys.stderr)
            continue
        print(f"==> {t.name}", file=sys.stderr)
        t.runner()


def build_all(
    root: str | None = None,
    config_path: str | None = None,
    config: _config.BuildConfig | None = None,
) -> None:
    """Run every registered target except ``cli_only`` ones and
    config-disabled ones.

    Order: every config-enabled vendor target (via the ``@vendors``
    expansion baked into ``house-footprints``'s deps), then
    ``house-footprints`` (if enabled), then ``house-step-models`` +
    ``house-schlib``, then ``house-pcblib``. Achieved by walking the
    dep graph from the two terminal targets ``house-pcblib`` and
    ``house-schlib``.

    Each target's config gate (see
    :meth:`_config.BuildConfig.is_target_enabled`) is consulted at
    execution time so a config flip between two ``build_all`` calls in
    the same process (the in-browser configurator does this whenever
    the user toggles a family) takes effect immediately without
    re-discovery.
    """
    cfg = discover(root, config_path=config_path, config=config)
    seen: set[str] = set()

    def run_chain(terminal: str) -> None:
        for n in _resolve_deps(terminal):
            if n in seen:
                continue
            t = _REGISTRY[n]
            if t.cli_only:
                continue
            if not cfg.is_target_enabled(n, t.kind):
                # Print a one-liner so the user can see why a target
                # they expected didn't run; matches the per-target
                # ``==>`` format so log-trawling stays consistent.
                print(f"--> skipping {t.name} (disabled by config)", file=sys.stderr)
                seen.add(n)
                continue
            print(f"==> {t.name}", file=sys.stderr)
            t.runner()
            seen.add(n)

    # ``standards`` is a leaf with no downstream consumer; list it
    # alongside the .PcbLib / .SchLib terminals so toggling its
    # artifact flag actually pulls the target into a `build_all`
    # invocation. The catch-all loop below would still pick it up,
    # but wiring it explicitly keeps the dependency story
    # symmetric with the in-browser runner in `hlcl-runner.ts`.
    for terminal in ("house-pcblib", "house-schlib", "standards"):
        if terminal in _REGISTRY:
            run_chain(terminal)

    # Catch any target the terminals didn't transitively pull in
    # (e.g. a future vendor with no downstream consumer). Skips
    # cli_only and the auto-generated manufacturer aggregates (whose
    # runner is a no-op anyway).
    for t in list(_REGISTRY.values()):
        if t.name in seen or t.cli_only or t.kind == AGGREGATE:
            continue
        run_chain(t.name)


# ---------------------------------------------------------------------------
# clean
# ---------------------------------------------------------------------------

def clean(root: str | None = None) -> None:
    """Remove the ``build/`` tree and every ``__pycache__`` directory
    under ``vendors/`` and ``house/``. Equivalent of the old
    ``make clean``."""
    base = os.path.abspath(root) if root else ROOT_DIR
    build_dir = os.path.join(base, "build")
    if os.path.isdir(build_dir):
        shutil.rmtree(build_dir)
    sweep_targets: list[str] = []
    for top in ("vendors", "house"):
        top_dir = os.path.join(base, top)
        if os.path.isdir(top_dir):
            sweep_targets.append(top_dir)
    for top_dir in sweep_targets:
        for dirpath, dirnames, _files in os.walk(top_dir):
            if "__pycache__" in dirnames:
                shutil.rmtree(os.path.join(dirpath, "__pycache__"))
                dirnames.remove("__pycache__")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

USAGE = """\
Usage: python build.py [--config <path>] [<target>|all|clean|--list]

  (no arg)            same as `all`
  --config <path>     load BuildConfig from <path> (JSON, validated
                      against `hlcl/build-config.schema.json`).
                      Defaults to `hlcl/factory-defaults.json` when
                      omitted; errors out if neither is available.
  all                 build every config-enabled target (excludes
                      `standards`)
  <target>            build one target plus its config-enabled deps
  clean               rm -rf build/ + __pycache__ (no config required)
  --list, -l          print every registered target with its
                      config-derived gate state
  --help, -h          show this message
"""


def _peel_config_argv(args: list[str]) -> str | None:
    """Pop ``--config <path>`` (or ``--config=<path>``) out of ``args``,
    returning the path or None. Mirrors :func:`_config._peel_config_argv`
    but operates on the local arg list rather than mutating
    ``sys.argv`` -- the build.py CLI parses its own args explicitly so
    we don't want :func:`_config.bootstrap` to also peel them."""
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--config":
            if i + 1 >= len(args):
                raise ValueError("--config requires a path argument")
            p = args[i + 1]
            del args[i : i + 2]
            return p
        if a.startswith("--config="):
            p = a[len("--config=") :]
            del args[i]
            return p
        i += 1
    return None


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)

    # Help / list / clean are config-agnostic short-circuits so that
    # `--list`, `--help`, and `clean` work even on a fresh clone where
    # `factory-defaults.json` hasn't been generated yet.
    if args[:1] in (["--help"], ["-h"]):
        sys.stdout.write(USAGE)
        return 0

    config_path = _peel_config_argv(args)

    if args[:1] in (["--list"], ["-l"]):
        # Discovery needs a config (because vendor / house modules
        # capture settings at import time). Use the requested config
        # if any, otherwise fall back to factory-defaults.
        cfg = discover(config_path=config_path)
        for t in list_targets():
            if t.cli_only:
                gate = "cli-only"
            elif cfg.is_target_enabled(t.name, t.kind):
                gate = "ON"
            else:
                gate = "off"
            print(f"  {t.name:30s}  {t.kind:10s}  [{gate}]")
        return 0

    if not args:
        build_all(config_path=config_path)
        return 0
    if len(args) != 1:
        sys.stderr.write(USAGE)
        return 2
    arg = args[0]
    if arg == "all":
        build_all(config_path=config_path)
        return 0
    if arg == "clean":
        # `clean` is purely a filesystem op; no config needed.
        clean()
        return 0
    discover(config_path=config_path)
    if arg not in _REGISTRY:
        print(
            f"error: unknown target {arg!r}; "
            f"run `python build.py --list` for the full list",
            file=sys.stderr,
        )
        return 2
    build_target(arg, config_path=config_path)
    return 0


if __name__ == "__main__":
    # Avoid the dual-module pitfall: when build.py is run as a script
    # Python loads it as ``__main__``, but a later ``from build import
    # register`` from inside a ``_build.py`` stub would otherwise
    # trigger a *second* fresh load of this file under the name
    # ``build`` -- yielding two copies of ``_REGISTRY``, with the
    # stubs registering into the wrong one. Aliasing
    # ``sys.modules["build"]`` to ``__main__`` makes the second
    # ``import build`` a cache hit and keeps the registry singleton.
    sys.modules.setdefault("build", sys.modules["__main__"])
    sys.exit(main())
