<script lang="ts">
	import { base } from '$app/paths';
	import SectionHeader from '../SectionHeader.svelte';

	const PAS_URL = `${base}/scripts/update_library_footprints.pas`;
	const PRJSCR_URL = `${base}/scripts/update_library_footprints.PrjScr`;

	const CONTACT_URL = 'https://jdbrinton.consulting/contact';

	/** Major ECAD platforms we do not target yet — contributors welcome. */
	const ecadContributorSections: { title: string; description: string }[] = [
		{
			title: 'Cadence Allegro',
			description:
				'HLCL does not yet support Cadence Allegro / OrCAD PCB: there is no Allegro symbol–footprint bridge or native library emitter in this repository today. We would love help from open-source contributors who know Cadence tooling and want to define a practical HLCL → Allegro workflow.'
		},
		{
			title: 'KiCad',
			description:
				'KiCad libraries (symbols, footprints, and 3D) are not generated by HLCL yet. If you want to help map HLCL outputs to KiCad conventions or build an exporter, we are eager to collaborate.'
		},
		{
			title: 'Siemens EDA (PADS Pro / Xpedition)',
			description:
				'HLCL does not produce PADS or Xpedition component or decal libraries. Contributors familiar with Siemens library formats could make a big difference here.'
		},
		{
			title: 'Autodesk Fusion (electronics / PCB)',
			description:
				'There is no Fusion- or Eagle-compatible library path from HLCL today. If you have experience with Fusion electronics libraries, we welcome ideas and patches.'
		}
	];
</script>

<SectionHeader
	title="Altium Designer"
	description="Use HLCL build outputs in Altium Designer — either as managed items in an Altium 365 workspace, or as conventional on-disk libraries."
/>

<div class="mt-10 space-y-14">
	<!-- ── Subsection: native (file-based) libraries ───────────────── -->
	<div>
		<h3 class="text-lg font-semibold tracking-tight text-ink-900">
			Use Libraries in Altium (Native)
		</h3>
		<p class="mt-1 text-sm text-ink-600">
			Without a workspace, add the per-vendor
			<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">.DbLib</code>
			files from
			<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">build/output/</code>
			to your project or to Installed Libraries. Each DbLib resolves
			<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">house.SchLib</code>
			and
			<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">house.PcbLib</code>
			next to it, so keep that folder copied or checked out as a single tree.
		</p>
		<section class="mt-5 rounded-lg border border-ink-200 bg-white p-6">
			<ol class="space-y-3 text-sm text-ink-700">
				{#each ['After each HLCL build, sync or replace your local copy of build/output/ (same relative layout as the generator produced).', 'In Altium: Components panel → File Libraries (or Project → Project Options → Search Paths) / Installed Libraries — add the vendor .DbLib files you need.', 'Place parts by MPN as usual; Altium looks up the row in the bound .xls and pulls the symbol from house.SchLib and footprints from house.PcbLib.', 'When you regenerate, overwrite the .xls, .DbLib, and house.* libraries together. Reload libraries or restart Altium if cached metadata looks stale.'] as step, i (i)}
					<li class="flex items-start gap-3">
						<span
							class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-accent-100 text-[10px] font-semibold text-accent-800"
							>{i + 1}</span
						>
						<span>{step}</span>
					</li>
				{/each}
			</ol>
			<p class="mt-4 text-xs text-ink-500">
				This path skips Library Importer and managed items — you are editing files on disk. The
				DelphiScript footprint-refresh workflow in the subsection below is for Altium 365 managed
				footprints only.
			</p>
		</section>
	</div>

	<!-- ── Subsection: Altium 365 ───────────────────────────────────── -->
	<div>
		<h3 class="text-lg font-semibold tracking-tight text-ink-900">
			Migrate to Altium 365 (Cloud Based Workspace)
		</h3>
		<p class="mt-1 text-sm text-ink-600">
			Import the generated library into an Altium Workspace and keep managed footprints up to date
			when the library is regenerated.
		</p>

		<!-- Two-column layout: import guide on the left, script download card on the right -->
		<div class="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]">
			<!-- ── Left column: workflow instructions ──────────────────────────── -->
			<div class="space-y-6">
				<!-- Initial import -->
				<section class="rounded-lg border border-ink-200 bg-white p-6">
					<h3
						class="flex items-center gap-2 text-sm font-semibold tracking-wider text-navy-700 uppercase"
					>
						<span
							class="flex h-5 w-5 items-center justify-center rounded-full bg-navy-900 text-[10px] font-bold text-white"
							>1</span
						>
						First-time import
					</h3>
					<p class="mt-3 text-sm text-ink-700">
						After generating the library for the first time, add the
						<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">.DbLib</code>
						files to your Altium project using the Library Importer:
					</p>
					<ol class="mt-3 space-y-2 text-sm text-ink-700">
						{#each ['In Altium Designer, open the Library Importer (File → Library Importer, or from the Explorer panel).', 'Add all .DbLib files from build/output/ as sources.', 'Choose the target Workspace folder and follow the wizard.', 'Altium creates managed component items and uploads them to the Workspace.'] as step, i (i)}
							<li class="flex items-start gap-3">
								<span
									class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-accent-100 text-[10px] font-semibold text-accent-800"
									>{i + 1}</span
								>
								<span>{step}</span>
							</li>
						{/each}
					</ol>
					<div
						class="mt-4 rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800"
					>
						<strong class="font-semibold"
							>Do not re-run Library Importer on subsequent builds.</strong
						>
						Library Importer has no "match existing" path — it will create duplicates instead of updating
						the items already in your Workspace. Use the DelphiScript workflow below for all subsequent
						updates.
					</div>
				</section>

				<!-- Updating footprints -->
				<section class="rounded-lg border border-ink-200 bg-white p-6">
					<h3
						class="flex items-center gap-2 text-sm font-semibold tracking-wider text-navy-700 uppercase"
					>
						<span
							class="flex h-5 w-5 items-center justify-center rounded-full bg-navy-900 text-[10px] font-bold text-white"
							>2</span
						>
						Updating managed footprints
					</h3>
					<p class="mt-3 text-sm text-ink-700">
						The <code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs"
							>update_library_footprints.pas</code
						>
						script walks every footprint in the focused multi-component PcbLib editor and replaces its
						geometry (all 2D/3D primitives, Description, Height) with the same-named footprint from the
						other open PcbLib (<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs"
							>house.PcbLib</code
						>). The footprint <strong>Name</strong> and all managed-item metadata (Item Revision, Source,
						Revision State) are preserved — Altium owns those.
					</p>

					<div class="mt-5">
						<h4 class="text-xs font-semibold tracking-wider text-ink-600 uppercase">
							One-time setup
						</h4>
						<ol class="mt-2 space-y-2 text-sm text-ink-700">
							{#each [{ step: "File → Open → update_library_footprints.PrjScr (loads the script project; appears in the Projects panel). Note: opening the bare .pas via File → Open won't enumerate its procedures in the Run Script dialog — the .PrjScr is required.", code: null }, { step: 'File → Open → build/output/house.PcbLib (the source library, must stay open during the run). The script auto-detects it — no path constant to edit.', code: null }] as item, i (i)}
								<li class="flex items-start gap-3">
									<span
										class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-ink-100 text-[10px] font-semibold text-ink-600"
										>{i + 1}</span
									>
									<div>
										<span>{item.step}</span>
										{#if item.code}
											<pre
												class="mt-1.5 overflow-x-auto rounded bg-ink-900 px-3 py-2 font-mono text-[11px] text-emerald-400">{item.code}</pre>
										{/if}
									</div>
								</li>
							{/each}
						</ol>
					</div>

					<div class="mt-6">
						<h4 class="text-xs font-semibold tracking-wider text-ink-600 uppercase">
							Per-batch workflow (repeat after each build)
						</h4>
						<ol class="mt-2 space-y-2 text-sm text-ink-700">
							{#each ['Components / Explorer panel → multi-select the PCC items you want to refresh (Ctrl-click / Shift-click) → right-click → Edit. Altium opens a single "Footprint Library [Footprints] (N)" tab. Click that tab so it\'s the focused document.', "File → Run Script… → in the Select Item to Run dialog, pick ReplaceManagedFootprints from update_library_footprints.pas. The script inventories both libraries, pre-flights every name and bails out with a full error list on any mismatch, then replaces every target footprint's primitives and ends with a confirmation dialog.", 'Visually verify the geometry against the source.', 'Ctrl+S to save the Footprint Library tab.', 'In the Projects panel, right-click the project → Save to Server. In the Edit Revision dialog, leave ✓ Update items related to enabled. Every PCC item in the batch gets a new revision, and every Workspace Component that references one of them auto-bumps (no manual relink on the CMP side).'] as step, i (i)}
								<li class="flex items-start gap-3">
									<span
										class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-accent-100 text-[10px] font-semibold text-accent-800"
										>{i + 1}</span
									>
									<span>{step}</span>
								</li>
							{/each}
						</ol>
						<p class="mt-3 text-xs text-ink-500">
							Realistic batch size: 50–200 items per pass. Altium will get unhappy if you try to
							Edit thousands of items at once.
						</p>
					</div>
				</section>

				<!-- Updating managed components -->
				<section class="rounded-lg border border-ink-200 bg-white p-6">
					<h3
						class="flex items-center gap-2 text-sm font-semibold tracking-wider text-navy-700 uppercase"
					>
						<span
							class="flex h-5 w-5 items-center justify-center rounded-full bg-navy-900 text-[10px] font-bold text-white"
							>3</span
						>
						Updating managed components
					</h3>
					<p class="mt-3 text-sm text-ink-700">
						Unlike footprints, there is no practical automated workflow for refreshing managed
						component records: Altium's <code
							class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">.CmpLib</code
						>
						API is proprietary, so HLCL cannot drive component-parameter updates the way the DelphiScript
						drives geometry. So, there are two practical methods to update managed components:
					</p>
					<ul class="mt-4 ml-2 space-y-4 border-l-2 border-ink-200 pl-5 text-sm text-ink-700">
						<li class="flex items-start gap-3">
							<span class="mt-0.5 shrink-0 font-semibold text-navy-700 tabular-nums">(a)</span>
							<div>
								<strong class="font-semibold text-ink-800">Spreadsheet → Workspace.</strong>
								In the Explorer panel, select <em>all</em> components in that vendor family,
								right-click, and choose <strong>Edit</strong>. Altium opens the managed-component
								editor with a spreadsheet-style tab named like
								<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">[TDK] (900)</code>
								— the bracketed name and count match your family (yours will differ). Under the hood this
								is a .CmpLib file. Open the matching per-vendor
								<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">.xls</code> under
								<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">build/output/</code>,
								then copy rows or parameter columns that changed from the workbook into the .CmpLib
								file. If there are more than 2000 components in the family, Altium will open
								multiple tabs, each one with less than 2000 components.
							</div>
						</li>
						<li class="flex items-start gap-3">
							<span class="mt-0.5 shrink-0 font-semibold text-navy-700 tabular-nums">(b)</span>
							<div>
								<strong class="font-semibold text-ink-800">Delete and re-import.</strong>
								Remove that vendor family from the Workspace and run
								<strong>Library Importer</strong> again (same idea as section&nbsp;1) for a clean import.
							</div>
						</li>
					</ul>
					<div
						class="mt-4 rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800"
					>
						<strong class="font-semibold">Footprints first on a re-import.</strong>
						If you delete and re-import a family, refresh footprints with section&nbsp;2
						<em>before</em>
						you import again. Otherwise you can end up with multiple managed footprints that share the
						same footprint name — duplicate geometry under different
						<code class="rounded bg-ink-100 px-1 py-0.5 font-mono text-xs">Item ID</code>'s.
					</div>
				</section>
			</div>

			<!-- ── Right column: script download card (sticky) ─────────────────── -->
			<aside class="space-y-4">
				<div class="sticky top-6 rounded-lg border border-navy-200 bg-navy-50 p-5 shadow-sm">
					<h3 class="text-sm font-semibold text-navy-900">DelphiScript download</h3>
					<p class="mt-1 text-xs text-ink-600">
						Both files must be downloaded together. Open the
						<code class="rounded bg-white/60 px-1 py-0.5 font-mono">.PrjScr</code>
						first — Altium's Run Script dialog only enumerates procedures from
						<code class="rounded bg-white/60 px-1 py-0.5 font-mono">.pas</code>
						files that are members of an open script project.
					</p>
					<div class="mt-4 flex flex-col gap-2">
						<a
							href={PAS_URL}
							download="update_library_footprints.pas"
							class="flex items-center gap-3 rounded-md border border-navy-200 bg-white px-4 py-3 text-sm font-medium text-navy-900 shadow-sm transition hover:border-navy-400 hover:bg-navy-50"
						>
							<svg class="h-5 w-5 shrink-0 text-navy-600" viewBox="0 0 20 20" fill="currentColor">
								<path
									fill-rule="evenodd"
									d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM10 3a1 1 0 011 1v6.586l1.293-1.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 011.414-1.414L9 10.586V4a1 1 0 011-1z"
									clip-rule="evenodd"
								/>
							</svg>
							<div class="min-w-0">
								<div class="truncate font-mono text-xs">update_library_footprints.pas</div>
								<div class="text-[11px] text-ink-500">Script source (DelphiScript)</div>
							</div>
						</a>
						<a
							href={PRJSCR_URL}
							download="update_library_footprints.PrjScr"
							class="flex items-center gap-3 rounded-md border border-navy-200 bg-white px-4 py-3 text-sm font-medium text-navy-900 shadow-sm transition hover:border-navy-400 hover:bg-navy-50"
						>
							<svg class="h-5 w-5 shrink-0 text-navy-600" viewBox="0 0 20 20" fill="currentColor">
								<path
									fill-rule="evenodd"
									d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM10 3a1 1 0 011 1v6.586l1.293-1.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 011.414-1.414L9 10.586V4a1 1 0 011-1z"
									clip-rule="evenodd"
								/>
							</svg>
							<div class="min-w-0">
								<div class="truncate font-mono text-xs">update_library_footprints.PrjScr</div>
								<div class="text-[11px] text-ink-500">Script project (required wrapper)</div>
							</div>
						</a>
					</div>

					<div class="mt-5 border-t border-navy-200 pt-4">
						<h4 class="text-xs font-semibold tracking-wider text-ink-600 uppercase">
							What gets replaced
						</h4>
						<ul class="mt-2 space-y-1 text-xs text-ink-700">
							{#each ['All 2D/3D primitives — pads, tracks, arcs, regions, fills, text, 3D bodies (with embedded STEP)', 'Footprint-level Description and Height'] as item (item)}
								<li class="flex items-start gap-1.5">
									<svg
										class="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-500"
										viewBox="0 0 20 20"
										fill="currentColor"
									>
										<path
											fill-rule="evenodd"
											d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
											clip-rule="evenodd"
										/>
									</svg>
									{item}
								</li>
							{/each}
						</ul>
						<h4 class="mt-3 text-xs font-semibold tracking-wider text-ink-600 uppercase">
							Left alone
						</h4>
						<ul class="mt-2 space-y-1 text-xs text-ink-700">
							{#each ['Footprint Name (preserves managed-item identity)', 'Item Revision, Source, Revision Details, Revision State'] as item (item)}
								<li class="flex items-start gap-1.5">
									<svg
										class="mt-0.5 h-3.5 w-3.5 shrink-0 text-ink-400"
										viewBox="0 0 20 20"
										fill="currentColor"
									>
										<path
											fill-rule="evenodd"
											d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
											clip-rule="evenodd"
										/>
									</svg>
									{item}
								</li>
							{/each}
						</ul>
					</div>
				</div>
			</aside>
		</div>
	</div>
</div>

<div class="mt-16 space-y-12 border-t border-ink-200 pt-14">
	{#each ecadContributorSections as block (block.title)}
		<div>
			<SectionHeader title={block.title} description={block.description} />
			<div class="mt-4">
				<a
					href={CONTACT_URL}
					target="_blank"
					rel="noopener noreferrer"
					class="inline-flex items-center justify-center gap-2 rounded-lg bg-accent-500 px-5 py-2.5 text-sm font-semibold text-navy-950 shadow-sm transition hover:bg-accent-400"
				>
					Contact about contributing
					<svg class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
						<path
							fill-rule="evenodd"
							d="M4.25 5.5a.75.75 0 01.75-.75h10.5a.75.75 0 01.75.75v8.5a.75.75 0 01-1.5 0V7.56l-8.22 8.22a.75.75 0 11-1.06-1.06L13.44 6.5H5.5a.75.75 0 01-.75-.75z"
							clip-rule="evenodd"
						/>
					</svg>
				</a>
			</div>
		</div>
	{/each}
</div>
