#!/usr/bin/env python
"""
Placeholder for a procedurally generated Murata ferrite-bead database.

build/murata-ferrite.xls is currently maintained by hand, NOT generated by
this script. This file marks where the generator will eventually live, once
we catch up with the negative work of replacing the hand-crafted workbook
with one built from datasheet-scraped part data -- matching the pattern
already in use for vendors/panasonic/panasonic-resistors.py.

Running this script today is intentionally a no-op so the hand-crafted
build/murata-ferrite.xls is never clobbered. When the time comes to fill
this in, write the BLM15 / BLM18 / BLM31 sheets along the same lines as
vendors/panasonic/panasonic-resistors.py and emit the workbook to OUTPUT_XLS via
wb.save(OUTPUT_XLS).

Expected shape (see docs/database-example.png and the 'Database Standards'
section of README.md for the canonical per-row schema):

    Sheets:   BLM15 (0402 / 1005 metric)
              BLM18 (0603 / 1608 metric)
              BLM31 (1206 / 3216 metric)
    Columns:  Comment, Description, MFG, MPN,
              DCR, Current, Imedance, Tr, Qual,
              Library Path, Library Ref,
              Footprint Path / Ref  x3  (IPC-7351 L / N / M density variants)

Note: "Imedance" (sic) is misspelled in the existing DbLib field mapping
(build/murata-ferrite.DbLib). The generator must emit the same misspelled
column header so the DbLib keeps resolving it, or both the DbLib and the
generator must be changed together.
"""

import os
import sys

BUILD_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "build")
OUTPUT_XLS = os.path.join(BUILD_DIR, "murata-ferrite.xls")

# TODO: build BLM15 / BLM18 / BLM31 sheets along the lines of
# vendors/panasonic/panasonic-resistors.py, then wb.save(OUTPUT_XLS).

print(
    "murata-ferrite.py is a placeholder; build/murata-ferrite.xls is "
    "currently maintained by hand. Nothing to do.",
    file=sys.stderr,
)
